# Generated by Django 4.0.2 on 2022-02-12 13:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RequestLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        db_index=True,
                        help_text="General-purpose free text field - useful for classifying requests.",
                        max_length=100,
                    ),
                ),
                (
                    "session_key",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                ("http_method", models.CharField(max_length=10)),
                ("request_uri", models.URLField(verbose_name="Request path")),
                (
                    "query_string",
                    models.CharField(blank=True, default="", max_length=1000),
                ),
                ("remote_addr", models.CharField(default="", max_length=100)),
                ("http_user_agent", models.CharField(default="", max_length=400)),
                ("http_referer", models.CharField(default="", max_length=400)),
                (
                    "duration",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Request duration (sec)"
                    ),
                ),
                (
                    "response_status_code",
                    models.IntegerField(
                        blank=True,
                        help_text="Response HTTP status code (2xx, 3xx, 4xx, 5xx, etc).",
                        null=True,
                    ),
                ),
                (
                    "response_content_length",
                    models.IntegerField(
                        blank=True,
                        help_text="Length of the response body in bytes.",
                        null=True,
                    ),
                ),
                (
                    "response_content_type",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Response Content-Type header.",
                        max_length=100,
                    ),
                ),
                (
                    "response_location",
                    models.CharField(
                        help_text="Response location in the event of a redirect (3xx).",
                        max_length=400,
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
