# Generated by Django 4.0.2 on 2022-02-20 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_logger', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestlog',
            name='reference',
        ),
        migrations.AddField(
            model_name='requestlog',
            name='view_func',
            field=models.CharField(blank=True, default='', help_text='View function path - taken from request.resolver_match._func_path', max_length=200),
        ),
    ]
