# Generated by Django 4.0.2 on 2022-02-12 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("request_logger", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="requestlog",
            name="response_class",
            field=models.CharField(default="", max_length=50),
        ),
    ]
